### ISSUE TITLE
Login Notice in header (simple)

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN-NL#47]
for both French and Italian

**Comment by cubap** [comment]
Two problems.
You should get an alert here that completes the login check: https://centerfordigitalhumanities.github.io/Newberry-French-paleography/www/manuscripts.html

The `/geti` appears to be blocked. The first issue you will encounter is that the HTTPS GitHub site does not want to load HTTP `geti`. That can be "fixed" in the future with an insecure custom DNS, so we can flick the settings and keep moving.

After that, it appears CORS is not enabled, so I can `/geti` from the address bar, where it is a simple GET, but not programmatically.

**Comment by cubap** [comment]
https://centerfordigitalhumanities.github.io/Newberry-French-paleography/www/manuscripts.html

You can watch the calls on this page. @thehabes do you think we need the login servlet to have CORS? Why wouldn't geti be working here do you think?

**Comment by thehabes** [comment]
https://stackoverflow.com/questions/41896847/cross-origin-cookies-and-session

JSESSIONs do not persist across origins.  `/geti` fails even after `/login` succeeds because the `/geti` call from your origin does not pass the JSESSIONID created by the `/login` from your origin.  Every time `/geti` from your origin comes through without handing over a JSESSIONID, a new JSESSION is created.  These newly created JSESSIONs do not have the `UID` stored in them, and so `int UID = ServletUtils.getUID(request, response);` is always `-1`.  This results in `403 Forbidden` responses because it appears as though you are not logged in to the `/geti` servlet.

Look to how we made this work for Tradamus.  Instead of relying on the session and setting up cross-origin authentication with JSESSIONIDs.  Add a `?user=user@email` parameter to your `/geti` call and fall into `verifyHostInList()`.  This will use `User.java#User(string email)` to get the user from the database to call `getUID()` on.  Then the `/geti` response will stop being -1.

**Comment by cubap** [comment]
This is a great explanation of why we won't implement this for this phase. It is a heavy lift that could be done in the future.
