### ISSUE TITLE
Recreate pages for user admin

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN-NL#5]
Some interfaces, like login/out, new account, team management do not exist anywhere yet.

**Comment by thehabes** [comment]
`login.html` created, and it uses the classic TPEN login logic seen at http://t-pen.org/TPEN/login.jsp.  I have also brought in `login.jsp` from TPEN28.  The login.html was never used by newberry, so it is crude but fully functional.  login.jsp is not quite as crude, and maybe we should just use it.  `loginCheck.jsp` will be reinstated for the jsp pages that use it.

There is no logout page.  The servlet in TPEN-NL is mapped to servlets.logout just like classic T-PEN, so that should just work.  logout.java is the same between projects, since UofT used logoutHook.java and added their own entry into web.xml.  

LoginHook.java and the web.xml entry for it have been removed.    
LogoutHook.java and the web.xml entry for it have been removed.    
login and logout in web.xml are now mapped to the classic T-PEN versions.

`project.html` and `buttons.html` exist for special char and XML management, and was brought in as a bandage.  The original envisioning of the Newberry stuff did not include project management.  Since it will now, and the functionality it wants is the same management that exists for TPEN28, I am going to reinstate the project and button management .jsp pages.  The HTML pages will be removed.  We will need to remember to **check the index issue**. 

We can factor out `updateMetadataByProjectIDServlet.java`, `RemoveProjectCharacter.java`, UpdateProjectTag.java`, `RemoveProjectTag.java`, `SaveNewProjectCharacter.java` and `SaveNewProjectXML.java`, which were all created to support the `project.html` and `buttons.html` special UI for newberry to access these management systems.  They are no longer needed if we are falling back to classic T-PEN project management.  

For team management, groups.jsp will be reinstated.  There was no code written for this for TPEN-NL in this area.  There are no servlets to worry about.

**Comment by thehabes** [comment]
The pieces were reinstated with success against the test TPEN database.  Will continue forward with testing against the TPEN-Newberry database from UofT.

**Comment by thehabes** [comment]
I think all the pages we need are there and stand up.  I am confident they are not all yet fully functional.
